## Numpy Assignment 1

- Student Name: Jovita Nagawa
- Student RegNo: 2025_HD07_26007U

### Instructions
- Please answer the exercises to the best of your knowledge.
- The assignment is out of 10 marks and will contribute partially to your final result.

In [4]:
#create numpy one dimentional array with 10 elements
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [7]:
#create an numpy array from a python list
pylist = [2,4,6,8,10]
numpy_array = np.array(pylist)
print(numpy_array)

[ 2  4  6  8 10]


In [9]:
# create an array of five values evenly spaced between 0 and 1
arr = np.linspace(0, 1, 5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [10]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 3
arr = np.random.normal(loc=0, scale=3, size=(3, 3))
print(arr)

[[-0.19039353 -4.28364105  3.24859809]
 [-3.12252575  0.44318144 -2.83161494]
 [ 0.12247063  0.12460615  1.7512653 ]]


In [11]:
#creat a 5x5 array with complex numbers
arr = np.zeros((5, 5), dtype=complex)
arr[:] = np.arange(25).reshape(5, 5) + 1j * np.arange(25).reshape(5, 5)
print(arr)


[[ 0. +0.j  1. +1.j  2. +2.j  3. +3.j  4. +4.j]
 [ 5. +5.j  6. +6.j  7. +7.j  8. +8.j  9. +9.j]
 [10.+10.j 11.+11.j 12.+12.j 13.+13.j 14.+14.j]
 [15.+15.j 16.+16.j 17.+17.j 18.+18.j 19.+19.j]
 [20.+20.j 21.+21.j 22.+22.j 23.+23.j 24.+24.j]]


In [13]:
#create a one dimentional array with 20 elements and return elements from 3 to 7
arr = np.arange(20)
subset = arr[3:8]
print(subset)

[3 4 5 6 7]


In [21]:
#create a 3x3 array of random integers and reverse elements of the first row
arr = np.random.randint(0, 10, size=(3, 3))
arr[0] = arr[0][::-1]
print(arr[0])


[1 3 6]


In [ ]:
#create 2 4x4 arrays and stack them both vertically and horizontally

In [ ]:
#what are the rules of numpy broadcasting?

In [ ]:
# create two 3X3 matrices that are incopatible and raise an error

In [ ]:
#create a 4x4 matrix with random integers and use a boolean mask to check for those above 4